### ISSUE TITLE
[BUG] tpos issues after update from v0.12.12 to v1.0.0

### ISSUE THREAD

**Issue by tlindi** [lnbits/lnbits#3110]
**Describe the bug**
tpos gives errors on log while updating from v0.12.12 to v1.0.0

Some times it led to situation where successful tpos update to 0.7.2 or 1.0.0 required tpos database to be cleared.

**To Reproduce**
Unfortunately I was not able to catch exact way to reproduce. But here are logs for later reference, if neeeded.

**Expected behavior**
tpos should update smoothly and no database clear needed.

**Screenshots**

**Desktop (please complete the following information):**

- LNbits version: [v0.12.12] andd [v1.0.0]
- Database: sqlite

**Additional context**

logs
a) one occurance:
------------------------
v0.12.12 Initial run /w python 3.9
------------------------
```
2025-04-12 14:15:19.80 | INFO | ✔️ All migrations done.
2025-04-12 14:15:19.80 | WARNING | Settings DB empty. Inserting default settings.
2025-04-12 14:15:19.84 | WARNING | Initialized settings from environment variables.
2025-04-12 14:15:19.89 | SUCCESS | ✔️ Admin UI is enabled. run `poetry run lnbits-cli superuser` to get the superuser.
2025-04-12 14:15:19.91 | INFO | Initialized webpush settings with generated VAPID key pair.
2025-04-12 14:15:19.91 | INFO | Pubkey: BNdaRglUJdALzAuieENClrdHmG1B56TvOY7_tgqu-jiz2ib3RgaZ-luOFJRsKiKuD5IAj-wLB_JwI_SHAG4nCZs
2025-04-12 14:15:19.91 | INFO | Starting LNbits
2025-04-12 14:15:19.91 | INFO | Version: 0.12.12
2025-04-12 14:15:19.91 | INFO | Baseurl: http://127.0.0.1:5000/
2025-04-12 14:15:19.91 | INFO | Host: 127.0.0.1
2025-04-12 14:15:19.91 | INFO | Port: 5500
2025-04-12 14:15:19.92 | INFO | Debug: False
2025-04-12 14:15:19.92 | INFO | Site title: LNbits
2025-04-12 14:15:19.92 | INFO | Funding source: VoidWallet
2025-04-12 14:15:19.92 | INFO | Data folder: ./data
2025-04-12 14:15:19.92 | INFO | Database: SQLite
2025-04-12 14:15:19.92 | INFO | Service fee: 0.0
2025-04-12 14:15:19.92 | INFO | Service fee max: 0
2025-04-12 14:15:19.92 | INFO | Service fee wallet: None
2025-04-12 14:15:19.92 | INFO | Connecting to backend VoidWallet...
2025-04-12 14:15:19.92 | WARNING | This backend does nothing, it is here just as a placeholder, you must configure an actual backend before being able to do anything useful with LNbits.
2025-04-12 14:15:19.92 | SUCCESS | ✔️ Backend VoidWallet connected and with a balance of 0 msat.
2025-04-12 14:15:19.99 | WARNING | Task: skipping pending check for VoidWallet
2025-04-12 14:15:19.99 | INFO | got a payment notification
2025-04-12 14:15:19.99 | INFO | Application startup complete.
2025-04-12 14:15:19.99 | INFO | Uvicorn running on http://127.0.0.1:5500 (Press CTRL+C to quit)
2025-04-12 14:15:20.12 | INFO | Installed Extensions (1):
2025-04-12 14:15:20.12 | INFO | tpos (0.7.2)
```
------------------------------
tpos was NOT shown installed on Extensions - and all list it was v0.0 (unfor no screen shot here)
------------------------------

------------------------
Update to v1.0.0 update python to 3.12 - No other changes - tpos error:
------------------------

```
025-04-12 14:21:07.54 | INFO | Started server process [116959]
2025-04-12 14:21:07.54 | INFO | Waiting for application startup.
running migration core.22
running migration core.23
running migration core.24
running migration core.25
running migration core.26
running migration core.27
2025-04-12 14:21:07.76 | INFO | Updating payments
2025-04-12 14:21:07.76 | INFO | Updating 0 to 1000
2025-04-12 14:21:07.76 | INFO | Payments count: 0
2025-04-12 14:21:07.76 | INFO | Payments updated
running migration core.28
running migration core.29
running migration core.30
running migration core.31
2025-04-12 14:21:09.06 | INFO | ✔️ All migrations done.
2025-04-12 14:21:09.19 | SUCCESS | ✔️ Admin UI is enabled. run `poetry run lnbits-cli superuser` to get the superuser.
2025-04-12 14:21:09.19 | INFO | Initialized webpush settings with generated VAPID key pair.
2025-04-12 14:21:09.19 | INFO | Pubkey: BNdaRglUJdALzAuieENClrdHmG1B56TvOY7_tgqu-jiz2ib3RgaZ-luOFJRsKiKuD5IAj-wLB_JwI_SHAG4nCZs
2025-04-12 14:21:09.23 | ERROR | cannot import name 'api_payment' from 'lnbits.core.views.api' (/home/<username_hidden>/lnbits.dev/lnbits/lnbits/core/views/api.py)
2025-04-12 14:21:09.23 | WARNING | Cannot import module for extension 'tpos'.
2025-04-12 14:21:09.36 | INFO | Installed Extensions (2):
2025-04-12 14:21:09.36 | INFO | tpos (0.0)
2025-04-12 14:21:09.36 | INFO | tpos (1.0.3)
2025-04-12 14:21:09.36 | ERROR | Could not load extension `tpos`: cannot import name 'api_payment' from 'lnbits.core.views.api' (/home/<username_hidden>/lnbits.dev/lnbits/lnbits/core/views/api.py)
2025-04-12 14:21:09.36 | INFO | Starting LNbits
2025-04-12 14:21:09.36 | INFO | Version: 1.0.0
2025-04-12 14:21:09.36 | INFO | Baseurl: http://127.0.0.1:5000/
2025-04-12 14:21:09.37 | INFO | Host: 127.0.0.1
2025-04-12 14:21:09.37 | INFO | Port: 5500
2025-04-12 14:21:09.37 | INFO | Debug: False
2025-04-12 14:21:09.37 | INFO | Site title: LNbits
2025-04-12 14:21:09.37 | INFO | Funding source: VoidWallet
2025-04-12 14:21:09.37 | INFO | Data folder: ./data
2025-04-12 14:21:09.37 | INFO | Database: SQLite
2025-04-12 14:21:09.37 | INFO | Service fee: 0.0
2025-04-12 14:21:09.37 | INFO | Service fee max: 0
2025-04-12 14:21:09.37 | INFO | Service fee wallet: None
2025-04-12 14:21:09.37 | INFO | Connecting to backend VoidWallet...
2025-04-12 14:21:09.37 | WARNING | This backend does nothing, it is here just as a placeholder, you must configure an actual backend before being able to do anything useful with LNbits.
2025-04-12 14:21:09.37 | SUCCESS | ✔️ Backend VoidWallet connected and with a balance of 0 msat.
2025-04-12 14:21:09.56 | WARNING | Task: skipping pending check for VoidWallet
2025-04-12 14:21:09.56 | INFO | got a payment notification
2025-04-12 14:21:09.56 | WARNING | This backend does nothing, it is here just as a placeholder, you must configure an actual backend before being able to do anything useful with LNbits.
2025-04-12 14:21:09.56 | INFO | Application startup complete.
2025-04-12 14:21:09.76 | INFO | Uvicorn running on http://127.0.0.1:5500 (Press CTRL+C to quit)
2025-04-12 14:21:09.77 | WARNING | This backend does nothing, it is here just as a placeholder, you must configure an actual backend before being able to do anything useful with LNbits.
```

After update it was show installed, but still v0.0

![Image](https://github.com/user-attachments/assets/3aad2239-15b9-4d3c-8b66-cc69e4d82872)

![Image](https://github.com/user-attachments/assets/24f240eb-cc77-404b-b130-913672c864ba)

b) 2nd case 
------------------------
first v1.0.0 start after update from v0.12.12 and python3.9 -> 3.12
------------------------

```
2025-04-12 17:14:21.28 | INFO | Started server process [247067]
2025-04-12 17:14:21.28 | INFO | Waiting for application startup.
2025-04-12 17:14:21.31 | ERROR | cannot import name 'api_payment' from 'lnbits.core.views.api' (/home/<OMIT_USER>/lnbits.dev/lnbits/lnbits/core/views/api.py)
2025-04-12 17:14:21.31 | ERROR | Error migrating extension tpos: Cannot import module for extension 'tpos'.
2025-04-12 17:14:21.34 | INFO | ✔️ All migrations done.
2025-04-12 17:14:21.51 | SUCCESS | ✔️ Admin UI is enabled. run `poetry run lnbits-cli superuser` to get the superuser.
2025-04-12 17:14:21.52 | INFO | Initialized webpush settings with generated VAPID key pair.
2025-04-12 17:14:21.52 | INFO | Pubkey: BGNHYOVCFopmC--ScCcgKgwdcpJckFBxrUlkE6F4_1J2kLUz1nu9HQu9_XpO8lmdyebDdLACoo-VEfpUTOCvN6c
2025-04-12 17:14:21.52 | INFO | Installed Extensions (1):
2025-04-12 17:14:21.52 | INFO | tpos (0.7.2)
2025-04-12 17:14:21.52 | ERROR | Could not load extension `tpos`: cannot import name 'api_payment' from 'lnbits.core.views.api' (/home/<OMIT_USER>/lnbits.dev/lnbits/lnbits/core/views/api.py)
2025-04-12 17:14:21.52 | INFO | Starting LNbits
2025-04-12 17:14:21.52 | INFO | Version: 1.0.0
2025-04-12 17:14:21.52 | INFO | Baseurl: http://127.0.0.1:5000/
2025-04-12 17:14:21.52 | INFO | Host: 127.0.0.1
2025-04-12 17:14:21.52 | INFO | Port: 5500
2025-04-12 17:14:21.52 | INFO | Debug: False
2025-04-12 17:14:21.52 | INFO | Site title: LNbits
2025-04-12 17:14:21.52 | INFO | Funding source: VoidWallet
2025-04-12 17:14:21.53 | INFO | Data folder: ./data
2025-04-12 17:14:21.53 | INFO | Database: SQLite
2025-04-12 17:14:21.53 | INFO | Service fee: 0.0
2025-04-12 17:14:21.53 | INFO | Service fee max: 0
2025-04-12 17:14:21.53 | INFO | Service fee wallet: None
2025-04-12 17:14:21.53 | INFO | Connecting to backend VoidWallet...
...

Enabling tpos and clicking Open on it:
```2025-04-12 17:16:25.82 | INFO | Enabling extension: tpos.
2025-04-12 17:16:25.84 | INFO | <OMIT_IP>:0 - "PUT /api/v1/extension/tpos/enable HTTP/1.1" 200
2025-04-12 17:16:26.31 | INFO | <OMIT_IP>:0 - "GET /api/v1/extension HTTP/1.1" 200
2025-04-12 17:16:26.42 | INFO | <OMIT_IP>:0 - "GET /extensions HTTP/1.1" 200
2025-04-12 17:16:26.53 | INFO | <OMIT_IP>:0 - "GET /api/v1/extension HTTP/1.1" 200
2025-04-12 17:16:28.23 | ERROR | 404: /tpos/ 404: Not Found
2025-04-12 17:16:28.27 | INFO | <OMIT_IP>:0 - "GET /tpos/ HTTP/1.1" 403
2025-04-12 17:16:28.45 | INFO | connection closed
```
After "Back" in browser Extensions page looked like this:

![Image](https://github.com/user-attachments/assets/4fbbc467-dc04-43f2-b6fb-1a01c64e638b)

Refresh, restored view to normal.

2025-04-12 17:31:30.34 | INFO | ('<OMIT_IP>', 0) - "WebSocket /api/v1/ws/0e7bc7948c1f4354a54948a9e2f7e44d" [accepted]
2025-04-12 17:31:30.34 | INFO | connection open
2025-04-12 17:31:30.40 | INFO | <OMIT_IP>:0 - "GET /extensions HTTP/1.1" 200
2025-04-12 17:31:30.41 | INFO | <OMIT_IP>:0 - "GET /api/v1/extension HTTP/1.1" 200
2025-04-12 17:31:30.52 | INFO | <OMIT_IP>:0 - "GET /api/v1/extension HTTP/1.1" 200
2025-04-12 17:31:32.20 | INFO | <OMIT_IP>:0 - "GET /service-worker.js HTTP/1.1" 200

**Comment by tlindi** [comment]
LNbits v1.0.0 tpos update to v1.0.3 brings into log following:
```2025-04-12 17:36:16.55 | INFO | Extracting extension tpos (1.0.3).
2025-04-12 17:36:16.89 | INFO | Extension TPoS (1.0.3) extracted.
running migration tpos.9
running migration tpos.10
running migration tpos.11
running migration tpos.12
2025-04-12 17:36:17.52 | INFO | Stopping background work for extension 'lnbits.extensions.tpos'.
2025-04-12 17:36:17.52 | WARNING | Failed to stop background work for 'lnbits.extensions.tpos'.
2025-04-12 17:36:17.52 | WARNING | cannot import name 'tpos_generic_router' from 'lnbits.extensions.tpos.views' (/home/azureuser/lnbits.dev/lnbits/lnbits/extensions/tpos/views.py)
2025-04-12 17:36:17.52 | INFO | Starting background work for extension 'lnbits.extensions.tpos'.
2025-04-12 17:36:17.52 | WARNING | Failed to start background work for 'lnbits.extensions.tpos'.
2025-04-12 17:36:17.52 | WARNING | cannot import name 'tpos_generic_router' from 'lnbits.extensions.tpos.views' (/home/azureuser/lnbits.dev/lnbits/lnbits/extensions/tpos/views.py)
2025-04-12 17:36:17.56 | INFO | 82.181.20.31:0 - "POST /api/v1/extension HTTP/1.1" 200
2025-04-12 17:36:17.62 | INFO | Activating extension: 'tpos'.
2025-04-12 17:36:17.64 | INFO | 82.181.20.31:0 - "PUT /api/v1/extension/tpos/activate HTTP/1.1" 200
2025-04-12 17:36:19.84 | INFO | 82.181.20.31:0 - "GET /api/v1/extension HTTP/1.1" 200
2025-04-12 17:36:20.08 | INFO | 82.181.20.31:0 - "GET /extensions HTTP/1.1" 200
2025-04-12 17:36:20.15 | INFO | 82.181.20.31:0 - "GET /static/js/base.js HTTP/1.1" 304
2025-04-12 17:36:20.19 | INFO | 82.181.20.31:0 - "GET /static/js/extensions.js HTTP/1.1" 304
2025-04-12 17:36:20.32 | INFO | 82.181.20.31:0 - "GET /api/v1/extension HTTP/1.1" 200
```

And tpos Open works.

So maybe issue of mandatory database delete was on issue somewhere between 0.12.x to v1.0.0-rcN.

**Comment by tlindi** [comment]
@talvasconcelos I have yet another system where tpos update fails, if you want logs or so. I'm not in hurry to get this tpos working so please let me know when you are onto this.

**Comment by motorina0** [comment]
> @motorina0 , do you spot anything weird in the logs?

no

**Comment by talvasconcelos** [comment]
@tlindi 
I reproduced the steps: 
- install 12.12 on a fresh install
- install tpos (0.7.4)
- create a tpos, paid an invoice
- shutdown
- update server to V1
- i get expected errors about the tpos extension, it's outdated now
- update tpos (v1.0.4 latest)
- everthing works as expected

I'm closing this one for now, please re open if you manage to discover a reproducible scenario

**Comment by tlindi** [comment]
dear devs

I have here v1.0.0 setup where issue is active. Debug says this as I try to update tpos from v0.7.2 to v1.0.4.

```
2025-05-05 12:27:46.01 | INFO | <PUBLIC_IP>:0 - "GET /api/v1/extension/tpos/releases HTTP/1.1" 200
2025-05-05 12:27:48.39 | INFO | Downloading extension tpos (1.0.4).
2025-05-05 12:27:49.50 | INFO | Extracting extension tpos (1.0.4).
2025-05-05 12:27:49.64 | INFO | Extension TPoS (1.0.4) extracted.
2025-05-05 12:27:49.65 | DEBUG | running migration tpos.4
2025-05-05 12:27:49.66 | WARNING | (sqlite3.OperationalError) table pos already exists
[SQL:
        CREATE TABLE tpos.pos (
            id TEXT PRIMARY KEY,
            wallet TEXT NOT NULL,
            name TEXT NOT NULL,
            currency TEXT NOT NULL,
            tip_wallet TEXT NULL,
            tip_options TEXT NULL,
            withdrawlimit INTEGER DEFAULT 0,
            withdrawpin INTEGER DEFAULT 878787,
            withdrawamt INTEGER DEFAULT 0,
            withdrawtime INTEGER NOT NULL DEFAULT 0,
            withdrawbtwn INTEGER NOT NULL DEFAULT 10
        );
    ]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2025-05-05 12:27:49.69 | ERROR | HTTPException 500: Failed to install extension 'tpos'.(1.0.4).
2025-05-05 12:27:49.70 | INFO | <PUBLIC_IP>:0 - "POST /api/v1/extension HTTP/1.1" 500
```
UI says:

![Image](https://github.com/user-attachments/assets/d6f9081b-fe13-4815-aeeb-2fe169107c79)

I'm happy help by what ever means needed.
