### ISSUE TITLE
LNDHUB errors after upgrade to lnbits 0.12.7 and LNDHUB 0.4.1 with CoreLightningWallet backend.

### ISSUE THREAD

**Issue by bitcoinlizard** [lnbits/lnbits#2538]
**Describe the bug**
LNDHUB errors after upgrade to lnbits 0.12.7 and LNDHUB 0.4.1 with CoreLightningWallet backend.  This worked correctly with lnbits 0.12.5 and LNDHUB 0.3.2.  I suspect this is related to:
https://github.com/lnbits/lnbits/issues/2524

**To Reproduce**
Pay or create an invoice with BlueWallet.  I'm able to pay the invoice with errors but I'm unable to create an invoice.  I receive these error messages:

```
AttributeError: 'CoreLightningWallet' object has no attribute 'invoice_status'. Did you mean: 'get_invoice_status'?
2024-05-26 12:31:02.74 | ERROR | lnbits.exceptions:exception_handler:55 | Exception: 'CoreLightningWallet' object has no attribute 'invoice_status'
2024-05-26 12:31:02.74 | INFO | 127.0.0.1:59818 - "GET /lndhub/ext/getuserinvoices?limit=20 HTTP/1.0" 500
2024-05-26 12:31:02.74 | ERROR | Exception in ASGI application
```

**Expected behavior**
Create and pay invoices with LNDHUB and BlueWallet.

- LNbits version: 0.12.7
- Database sqlite

**Additional context**
This worked correctly with lnbits 0.12.5 and LNDHUB 0.3.2.

**Comment by iWarpBTC** [comment]
Thanks for the issue. This was addressed in https://github.com/lnbits/lndhub/pull/31 and should be fine in the next lndhub release.

**Comment by dni** [comment]
https://github.com/lnbits/lnbits-extensions/pull/357

**Comment by dni** [comment]
https://github.com/lnbits/lndhub/releases/tag/v0.4.2
