### ISSUE TITLE
[BUG] Boltcards extension fail to update a card after update to v.1.0.0

### ISSUE THREAD

**Issue by ElucGeek** [lnbits/lnbits#3108]
After updating from V.0.12.12 to V1.0.0 my existing boltcards are still working but I cannot modify them nor delete them nor create new ones.

When I try to edit an existing boltcard I got this error:
update_card() got an unexpected keyword argument 'card_name' 500

When I try to delete a card, I got no error but nothing happen, it's still here (of course not working as I wipe it before clicking delete).

When I try to setup a new card I got this error (redacted all sensible data with XXXXX):

(sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $7: 100 (expected str, got int) [SQL: INSERT INTO boltcards.cards ( id, uid, external_id, wallet, card_name, counter, tx_limit, daily_limit, enable, k0, k1, k2, otp ) VALUES ( %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s ) ] [parameters: ('XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXX', 'Test card', 1, 100, 500, True, 'XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXXXX')] (Background on this error at: https://sqlalche.me/e/14/dbapi) 

- LNbits version: V1.0.0
- Database postgres
- Installed and updated with poetry under Ubuntu

**Comment by tlindi** [comment]
I confim edit gives:

![Image](https://github.com/user-attachments/assets/781a7007-623c-4548-851c-d764192f9ade)

**Comment by talvasconcelos** [comment]
The issue is a mismatch in the DB for type string and integer, that only happens in postgres (sqlite doesn't care about typing). Fix is in the works...

**Comment by tlindi** [comment]
I'm not running on postgres.
